name: Latest Algotrading101 blog post workflow
on:
  schedule:
    # Runs every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: IgorWounds/IgorWounds/blog-post-workflow@master
        with:
          comment_tag_name: "Algotrading"
          feed_list: "https://algotrading101.com/learn/feed/"
          commit_message: "Update algotrading101.com blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
